[package]
name = "luckee-incentive"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
library = []

[dependencies]
cosmwasm-schema = "1.5"
cosmwasm-std = "2.2.2"
cosmwasm-storage = "1.5"
cw-storage-plus = "2.0"
cw2 = "1.0"
cw-utils = "1.0"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
luckee-incentive = { path = ".", features = [] }
cw-multi-test = "0.20"
proptest = "1.0"
